create table if not exists tracked_products (
  id bigint generated by default as identity primary key,
  product_id text not null,
  product_name text not null,
  product_url text not null,
  selected_option text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists scrape_history (
  id bigint generated by default as identity primary key,
  tracked_product_id bigint not null references tracked_products(id) on delete cascade,
  timestamp timestamptz not null default now(),
  price numeric,
  stock text,
  outcome text not null check (outcome in ('success','retried','failed')),
  attempt_number integer not null default 1,
  error_message text,
  method text
);

create index if not exists scrape_history_product_time_idx on scrape_history(tracked_product_id, timestamp desc);
